package constants

import "regexp"

var TOKENS = map[TokenType]*regexp.Regexp{
	FROM:         FROMREGEX,
	WORKDIR:      WORKDIRREGEX,
	COMMENTLINE:  COMMENTLINEREGEX,
	CREATEFOLDER: CREATEFOLDERREGEX,
	CREATEFILE:   CREATEFILEREGEX,
	DELETEFOLDER: DELETEFOLDERREGEX,
	DELETEFILE:   DELETEFILEREGEX,
	COPYFOLDER:   COPYFOLDERREGEX,
	COPYFILE:     COPYFILEREGEX,
	MOVEFOLDER:   MOVEFOLDERREGEX,
	MOVEFILE:     MOVEFILEREGEX,
	CHMOD:        CHMODREGEX,
	CHOWN:        CHOWNREGEX,
}
